title: 'Weeds detection'
description: Classify crops and weeds
about: This is a weeds detection classifier implemented with Fastai library.

  The project was build by [Abdel-Aziz BINGUITCHA-FARE](https://github.com/abdelino17).

  More info and the source code can be found below.

  [Web app](https://weeds-detection.herokuapp.com)

code: https://github.com/abdelino17/weeds-detection

sampleImages:
  - name: Black-grass (Weed)
    url: https://commons.wikimedia.org/wiki/File:Black-grass.png
  - name: Fat Hen (Weed)
    url: https://commons.wikimedia.org/wiki/File:Fat-hen.png
  - name: Maize (Crop)
    url: https://commons.wikimedia.org/wiki/File:Maize.png
  - name: Sugar Beet (Crop)
    url: https://commons.wikimedia.org/wiki/File:Sugar-beet.png
