title: 'Weeds detection'

description: Let's try to classify crops and weeds

about: This is a weeds detection classifier implemented with Fastai library.

  The project was build by [Abdel-Aziz BINGUITCHA-FARE](https://github.com/abdelino17).

  More info and the source code can be found below.

  [Web app](https://weeds-detection.herokuapp.com)

code: https://github.com/abdelino17/weeds-detection

sampleImages:
  - name: Black-grass (Weed)
    url: https://upload.wikimedia.org/wikipedia/commons/f/f7/Black-grass.png
  - name: Fat Hen (Weed)
    url: https://upload.wikimedia.org/wikipedia/commons/a/a8/Fat-hen.png
  - name: Maize (Crop)
    url: https://upload.wikimedia.org/wikipedia/commons/3/33/Maize.png
  - name: Sugar Beet (Crop)
    url: https://upload.wikimedia.org/wikipedia/commons/c/c7/Sugar-beet.png
